In [1]:
angle = 0
while True:
    angle += 22.5
    print(angle)
    if angle >= 360:
        break

22.5
45.0
67.5
90.0
112.5
135.0
157.5
180.0
202.5
225.0
247.5
270.0
292.5
315.0
337.5
360.0


In [49]:
import numpy as np

x = 0
y = 0

if y >= 0:
    x = -x
    alfa=np.rad2deg(np.arctan2(y, x))
else:
    alfa = -np.rad2deg(np.arctan2(y, x)) + 180

print(alfa)




0.0


In [9]:
import numpy as np

lst = np.matrix('0 0 0 1; 1 0 1 0; 0 1 0 0; 1 0 0 1')
print(lst)

element_size = 2

resize_img = np.zeros((lst.shape[0]*element_size, lst.shape[1]*element_size), dtype=np.uint8)

for y in range(lst.shape[0]):
    for x in range(lst.shape[1]):
        if lst[y, x] == 1:
            #print(y*element_size,element_size*y+element_size, x*element_size,element_size*x+element_size)
            resize_img[y*element_size:element_size*y+element_size, x*element_size:element_size*x+element_size] = np.ones((element_size, element_size), dtype=np.uint8)*255

print(resize_img)

[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 0]
 [1 0 0 1]]
[[  0   0   0   0   0   0 255 255]
 [  0   0   0   0   0   0 255 255]
 [255 255   0   0 255 255   0   0]
 [255 255   0   0 255 255   0   0]
 [  0   0 255 255   0   0   0   0]
 [  0   0 255 255   0   0   0   0]
 [255 255   0   0   0   0 255 255]
 [255 255   0   0   0   0 255 255]]


In [2]:
a = 2
fun = lambda x: x + a

print(fun(2))

4
